export { Main } from "./main/ui/Main.tsx"
export { Products } from "./products/ui/Products.tsx"
export { Feedback } from "./feedback/ui/Feedback.tsx"
export { Contact } from "./contact/Contact.tsx"
export { Footer } from "./footer/ui/Footer.tsx"
export { Header } from "./header/ui/Header.tsx"
